POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFub3RoZXIiLCJpZCI6IjYxZDY2OTMzMTk0ZWFhODg1ZTM4ODE4MCIsImlhdCI6MTY0MTQ1ODYwOH0.W9uFqMZSMpg-7VPhJY52AtTOoz-YdAjgyrdZ7M5deGY

{
  "title": "My First Blog",
  "author": "John Doe",
  "url": "wordpress.com/JohnDoeBlog",
  "likes": 6
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFub3RoZXIiLCJpZCI6IjYxZDY2OTMzMTk0ZWFhODg1ZTM4ODE4MCIsImlhdCI6MTY0MTQ1NTQ3N30.TS4lbz5j7oW1reeGw_9iBKwOYYQw_rUkZ3rrYtJn9r4

{
  "title": "10 SUB SPECIAL",
  "author": "The Mincrafting Guy",
  "url": "youtube.com/channel/wJuw7Isj91G",
  "likes": 4
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "10 SUB SPECIAL (Reupload)",
  "author": "The Mincrafting Guy",
  "url": "youtube.com/channel/wJuw7Isj91G",
  "likes": 4
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "I BEAT MINECRAFT WHILE 3 PEOPLE TRIED TO STOP ME (it was hard)",
  "author": "The Mincrafting Guy",
  "url": "youtube.com/channel/wJuw7Isj91G",
  "likes": 267390
}

###
Get http://localhost:3003/api/blogs

###
DELETE http://localhost:3003/api/blogs/61d6abc308df6ed461b66920
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFub3RoZXIiLCJpZCI6IjYxZDY2OTMzMTk0ZWFhODg1ZTM4ODE4MCIsImlhdCI6MTY0MTQ1ODgyM30.jEAWCS2wVYb_Wx86Ay2GX6aZmXZBUibKcdoXp3GTYuQ

###
Put http://localhost:3003/api/blogs/61c05577232d6d33cf8b7bd3
Content-Type: application/json

{
  "title": "I BEAT MINECRAFT WHILE 3 PEOPLE TRIED TO STOP ME (it was hard)",
  "author": "The Mincrafting Guy",
  "url": "youtube.com/channel/wJuw7Isj91G",
  "likes": 267390
}

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYxZDY2MWU1OTUyNGU0ZGIxYmJkOGIxZCIsImlhdCI6MTY0MTQ1NDEwOH0.eW7pSSkhoPW3QzlPtY8QEgFEuQSNG_Dsn_XKbF72e38